# Generated by Django 5.0 on 2023-12-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_text",
            field=models.TextField(default="Insert a Description", max_length=1000),
        ),
    ]
