# Generated by Django 5.0 on 2023-12-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_description_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku_text",
            field=models.CharField(default="noSku", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="upc_text",
            field=models.CharField(default="noUpc", max_length=15),
        ),
    ]
