# Generated by Django 5.0 on 2023-12-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_sku_text_product_upc_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_number",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="price_number",
            field=models.FloatField(default=0),
        ),
    ]
