# Generated by Django 5.0 on 2023-12-15 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_cost_number_product_price_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="ProductInfo",
        ),
    ]
