# Generated by Django 5.0 on 2023-12-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_rename_product_productinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="condition",
            field=models.CharField(
                choices=[
                    ("BN", "Brand New"),
                    ("LN", "Like New"),
                    ("AC", "Acceptable"),
                    ("DA", "Damage"),
                    ("MP", "Missing Parts"),
                ],
                default="Set a Condition",
                max_length=20,
            ),
        ),
    ]
