# Generated by Django 5.0 on 2023-12-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_productinfo_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="rack_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productinfo",
            name="storage_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="condition",
            field=models.CharField(
                choices=[
                    ("BN", "Brand New"),
                    ("LN", "Like New"),
                    ("AC", "Acceptable"),
                    ("DA", "Damage"),
                    ("MP", "Missing Parts"),
                ],
                default="LN",
                max_length=20,
            ),
        ),
    ]
