# Generated by Django 5.0 on 2023-12-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0007_productinfo_rack_number_productinfo_storage_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="item_number",
            field=models.IntegerField(default=0),
        ),
    ]
