# Generated by Django 5.0 on 2023-12-21 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_productinfo_item_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinfo",
            name="condition",
            field=models.CharField(
                choices=[
                    ("BN", "Brand New"),
                    ("LN", "Like New"),
                    ("AC", "Acceptable"),
                    ("DA", "Damage"),
                    ("MP", "Missing Parts"),
                ],
                default="LN",
                max_length=20,
                verbose_name="Condition",
            ),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="cost_number",
            field=models.FloatField(default=0, verbose_name="Cost"),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="description_text",
            field=models.TextField(
                default="Insert a Description",
                max_length=1000,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="item_number",
            field=models.IntegerField(default=0, verbose_name="Item number"),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="price_number",
            field=models.FloatField(default=0, verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="rack_number",
            field=models.IntegerField(default=0, verbose_name="Rack number"),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="sku_text",
            field=models.CharField(default="noSku", max_length=20, verbose_name="SKU"),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="storage_number",
            field=models.IntegerField(default=0, verbose_name="Storage Number"),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="title_text",
            field=models.CharField(max_length=80, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="upc_text",
            field=models.CharField(default="noUpc", max_length=15, verbose_name="UPC"),
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("alt_text", models.CharField(max_length=255)),
                (
                    "onProduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productinfo",
                    ),
                ),
            ],
        ),
    ]
