# Generated by Django 5.0 on 2023-12-22 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_productinfo_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="onProduct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.productinfo",
            ),
        ),
    ]
