# Generated by Django 5.0 on 2023-12-23 21:10

import s3direct.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_alter_images_onproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image_url",
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
