# Generated by Django 5.0 on 2023-12-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_images_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image_url",
            field=models.URLField(),
        ),
    ]
