# Generated by Django 5.0 on 2023-12-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_alter_images_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image_url",
            field=models.ImageField(upload_to=""),
        ),
    ]
