# Generated by Django 5.0 on 2023-12-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_alter_productinfo_title_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinfo",
            name="description_text",
            field=models.TextField(
                default="Insert a Description",
                max_length=5000,
                verbose_name="Description",
            ),
        ),
    ]
