# Generated by Django 5.0 on 2023-12-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_alter_productinfo_description_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="show_onStore",
            field=models.BooleanField(default=True, verbose_name="Show in store?"),
        ),
        migrations.AddField(
            model_name="productinfo",
            name="sold",
            field=models.BooleanField(default=False, verbose_name="Has been sold?"),
        ),
    ]
