# Generated by Django 5.0 on 2024-02-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_productinfo_show_onstore_productinfo_sold"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_text", models.CharField(max_length=75, verbose_name="Category")),
            ],
        ),
        migrations.AddField(
            model_name="productinfo",
            name="category",
            field=models.ManyToManyField(to="products.category"),
        ),
    ]
