# Generated by Django 5.0 on 2025-03-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_category_name_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='show_onStore',
            new_name='show_onstore',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='sold',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='quantity',
            field=models.BooleanField(default=0, verbose_name='Quatity'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='description_text',
            field=models.TextField(max_length=5000, verbose_name='Description'),
        ),
    ]
