# Generated by Django 5.0 on 2025-03-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_rename_show_onstore_productinfo_show_onstore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quatity'),
        ),
    ]
